[workspace]
resolver = "3"
members = ["core"]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
license = "MIT OR Apache-2.0"
repository = "https://github.com/themane/turnnet"
publish = false

[workspace.dependencies]
prost = "0.14"
prost-build = "0.14"
bytes = "1"
blake3 = "1"
rand_core = "0.9"
thiserror = "2"
proptest = "1"
rand_chacha = "0.9"

[workspace.lints.rust]
unsafe_code = "forbid"
missing_debug_implementations = "warn"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
